basePath: /
host: ws-ulbi.herokuapp.com
info:
  contact:
    email: indra@ulbi.ac.id
    name: API Support
    url: https://github.com/indrariksa
  description: This is a sample swagger for Fiber
  title: TES SWAG
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
